services:
  - type: web
    name: krishisahayak-app
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
