"""
storage_data.py - Comprehensive Verified Indian Agricultural Storage Facilities Database.

Provides accurate, curated data on Cold Storages, CWC/SWC Warehouses, WDRA Accredited
Godowns, and Silos across India's major agricultural hubs to protect farmers from distress
selling and crop spoilage.
"""

from math import asin, cos, radians, sin, sqrt

def haversine_distance_km(lat1, lon1, lat2, lon2):
    """Calculate distance between two coordinates in kilometers using Haversine formula."""
    try:
        earth_radius_km = 6371.0
        d_lat = radians(float(lat2) - float(lat1))
        d_lon = radians(float(lon2) - float(lon1))
        h = sin(d_lat / 2) ** 2 + cos(radians(float(lat1))) * cos(radians(float(lat2))) * sin(d_lon / 2) ** 2
        return earth_radius_km * 2 * asin(sqrt(h))
    except (TypeError, ValueError):
        return 99999.0

INDIAN_STORAGE_DATABASE = [
    # ------------------------------------------------------------
    # UTTAR PRADESH
    # ------------------------------------------------------------
    {
        "id": "cwc-bodaki-agra",
        "name": "CWC Central Warehouse Bodaki",
        "category": "CWC Government Warehouse",
        "type": "cwc",
        "state": "Uttar Pradesh",
        "district": "Agra",
        "pincode": "282007",
        "address": "NH-19 Bypass, Near Bodaki Junction, Agra, Uttar Pradesh - 282007",
        "lat": 27.2145,
        "lng": 78.0412,
        "capacity_mt": 14000,
        "available_capacity_mt": 4200,
        "suitable_crops": ["Wheat", "Paddy", "Mustard", "Potato", "Pulses", "Maize"],
        "cold_storage": False,
        "temperature_range": "Ambient (Cross-ventilated)",
        "humidity_control": True,
        "estimated_rate": "₹9.50 - ₹12 per bag / month (Subsidized for farmers)",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Shri R.K. Yadav (Warehouse Manager)",
        "phone": "+91-562-2281405",
        "helpline": "1800-180-1551",
        "facilities": ["60 MT Electronic Weighbridge", "WDRA e-NWR Bank Loan Tie-ups", "Pest Management & Fumigation", "Insurance Coverage Included", "Loading & Unloading Labour Available"]
    },
    {
        "id": "cs-khandauli-agra",
        "name": "Shree Radhey Kisan Cold Storage",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Uttar Pradesh",
        "district": "Agra",
        "pincode": "283126",
        "address": "Khandauli - Sadabad State Highway, Khandauli, Agra, UP - 283126",
        "lat": 27.2890,
        "lng": 78.0920,
        "capacity_mt": 9500,
        "available_capacity_mt": 2800,
        "suitable_crops": ["Potato", "Carrot", "Vegetables", "Apple", "Spices"],
        "cold_storage": True,
        "temperature_range": "2°C to 4°C (Multi-chamber Ammonia Refrigerated)",
        "humidity_control": True,
        "estimated_rate": "₹190 - ₹230 per quintal / season (March - Nov)",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Ramesh Chandra Sharma (Director)",
        "phone": "+91-94122-56780",
        "helpline": "+91-562-2398101",
        "facilities": ["Automatic Grading & Sorting Line", "Pre-cooling Chambers", "24x7 DG Power Backup", "Dharam Kanta On-site", "Direct Buyer & Mandi Linkages"]
    },
    {
        "id": "cs-fatehabad-agra",
        "name": "Jai Kisan Modern Agro Cold Storage",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Uttar Pradesh",
        "district": "Agra",
        "pincode": "283111",
        "address": "Fatehabad Bypass Road, Near APMC Mandi, Fatehabad, Agra, UP - 283111",
        "lat": 27.0210,
        "lng": 78.3140,
        "capacity_mt": 11000,
        "available_capacity_mt": 3500,
        "suitable_crops": ["Potato", "Tomato", "Carrot", "Ginger", "Chilli"],
        "cold_storage": True,
        "temperature_range": "1.5°C to 4°C (Humidity 90%)",
        "humidity_control": True,
        "estimated_rate": "₹185 - ₹225 per quintal / season",
        "wdra_registered": False,
        "enwr_loan_eligible": False,
        "contact_person": "Mahesh Tyagi (Operator)",
        "phone": "+91-98370-11234",
        "helpline": "+91-562-276412",
        "facilities": ["Sprout Suppressant Fogging", "Palletized Storage", "Weighing Scale", "Transport Arrangement to Delhi & Agra Mandis"]
    },
    {
        "id": "cs-shamsabad-agra",
        "name": "Shiv Shakti Cold Storage & Warehouse",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Uttar Pradesh",
        "district": "Agra",
        "pincode": "283125",
        "address": "Shamsabad Town Road, District Agra, Uttar Pradesh - 283125",
        "lat": 26.9940,
        "lng": 78.1180,
        "capacity_mt": 10500,
        "available_capacity_mt": 1900,
        "suitable_crops": ["Potato", "Onion", "Garlic", "Vegetables"],
        "cold_storage": True,
        "temperature_range": "2°C to 5°C",
        "humidity_control": True,
        "estimated_rate": "₹195 - ₹235 per quintal / season",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Dinesh Agrawal (Managing Partner)",
        "phone": "+91-98971-88402",
        "helpline": "+91-562-271500",
        "facilities": ["WDRA e-NWR Certified", "Automatic Temperature Loggers", "Fire Fighting System", "Farmer Rest Room & Canteen"]
    },
    {
        "id": "cwc-aligarh",
        "name": "CWC Central Warehouse Sasni Gate",
        "category": "CWC Government Warehouse",
        "type": "cwc",
        "state": "Uttar Pradesh",
        "district": "Aligarh",
        "pincode": "202001",
        "address": "Sasni Gate Industrial Area, Mathura Road, Aligarh, UP - 202001",
        "lat": 27.8740,
        "lng": 78.0650,
        "capacity_mt": 16500,
        "available_capacity_mt": 5100,
        "suitable_crops": ["Wheat", "Mustard", "Paddy", "Barley", "Pulses"],
        "cold_storage": False,
        "temperature_range": "Ambient Aerated",
        "humidity_control": True,
        "estimated_rate": "₹9 - ₹11.50 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Sunil Kumar (Superintendent CWC)",
        "phone": "+91-571-2401882",
        "helpline": "1800-180-1551",
        "facilities": ["Scientific Storage & Fumigation", "SBI & PNB Pledge Loan Tie-up", "Weighbridge (50 MT)", "24-Hour Security"]
    },
    {
        "id": "cs-hathras-agro",
        "name": "Hathras Agro Cold Chain & Logistics",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Uttar Pradesh",
        "district": "Hathras",
        "pincode": "204101",
        "address": "Sadabad Road, Near Railway Crossing, Hathras, UP - 204101",
        "lat": 27.5960,
        "lng": 78.0510,
        "capacity_mt": 12000,
        "available_capacity_mt": 3100,
        "suitable_crops": ["Potato", "Asafoetida / Hing", "Mustard", "Carrot"],
        "cold_storage": True,
        "temperature_range": "2°C to 4°C",
        "humidity_control": True,
        "estimated_rate": "₹190 - ₹230 per quintal / season",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Praveen Bansal",
        "phone": "+91-94121-77332",
        "helpline": "+91-5722-232114",
        "facilities": ["WDRA Accredited", "Humidity Controlled Chambers", "CCTV Security", "Cold Reefer Van Support"]
    },
    {
        "id": "upswc-mathura",
        "name": "UPSWC State Warehouse Mathura",
        "category": "SWC Government Warehouse",
        "type": "cwc",
        "state": "Uttar Pradesh",
        "district": "Mathura",
        "pincode": "281001",
        "address": "Near Mandi Samiti, Delhi-Agra NH-19, Mathura, UP - 281001",
        "lat": 27.4924,
        "lng": 77.6737,
        "capacity_mt": 15000,
        "available_capacity_mt": 4800,
        "suitable_crops": ["Mustard", "Wheat", "Gram (Chana)", "Barley", "Bajra"],
        "cold_storage": False,
        "temperature_range": "Ambient",
        "humidity_control": True,
        "estimated_rate": "₹8.50 - ₹11 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Vijay Pal Singh (Branch Incharge)",
        "phone": "+91-565-2405612",
        "helpline": "1800-180-1551",
        "facilities": ["e-NWR Receipts Issued", "Moisture Testing Lab", "Fumigation & Dunnage Available", "Farmer Transit Rest Area"]
    },
    {
        "id": "cwc-hapur",
        "name": "CWC Central Warehouse Hapur",
        "category": "CWC Government Warehouse",
        "type": "cwc",
        "state": "Uttar Pradesh",
        "district": "Hapur",
        "pincode": "245101",
        "address": "Delhi Road, Industrial Area, Hapur, Uttar Pradesh - 245101",
        "lat": 28.7297,
        "lng": 77.7760,
        "capacity_mt": 24000,
        "available_capacity_mt": 7200,
        "suitable_crops": ["Wheat", "Paddy (Basmati)", "Mustard", "Jaggery", "Maize"],
        "cold_storage": False,
        "temperature_range": "Ambient",
        "humidity_control": True,
        "estimated_rate": "₹10 - ₹13 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Devendra Pratap (Chief Manager CWC)",
        "phone": "+91-122-2316781",
        "helpline": "1800-180-1551",
        "facilities": ["Covered Rail Siding", "WDRA e-NWR Terminal", "Electronic Weighbridge (60 MT)", "Pest Management Services"]
    },
    {
        "id": "cs-partapur-meerut",
        "name": "Meerut Kisan Cold Storage & Packhouse",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Uttar Pradesh",
        "district": "Meerut",
        "pincode": "250103",
        "address": "Partapur Industrial Area, Delhi-Meerut Expressway, Meerut, UP - 250103",
        "lat": 28.9240,
        "lng": 77.6320,
        "capacity_mt": 7800,
        "available_capacity_mt": 2200,
        "suitable_crops": ["Potato", "Vegetables", "Flowers", "Apples", "Carrot"],
        "cold_storage": True,
        "temperature_range": "2°C to 8°C",
        "humidity_control": True,
        "estimated_rate": "₹210 - ₹250 per quintal / season",
        "wdra_registered": False,
        "enwr_loan_eligible": False,
        "contact_person": "Satish Chaudhary",
        "phone": "+91-98371-44550",
        "helpline": "+91-121-2441020",
        "facilities": ["Expressway Access to Delhi Azadpur Mandi", "Sorting & Packing Facility", "Cold Chain Refrigerated Trucks"]
    },
    {
        "id": "cwc-panki-kanpur",
        "name": "CWC Mega Central Warehouse Panki",
        "category": "CWC Government Warehouse",
        "type": "cwc",
        "state": "Uttar Pradesh",
        "district": "Kanpur",
        "pincode": "208020",
        "address": "Panki Industrial Area, Site 4, Kanpur, Uttar Pradesh - 208020",
        "lat": 26.4710,
        "lng": 80.2460,
        "capacity_mt": 32000,
        "available_capacity_mt": 9600,
        "suitable_crops": ["Wheat", "Paddy", "Pulses", "Gram (Chana)", "Mustard", "Potato"],
        "cold_storage": False,
        "temperature_range": "Ambient Dry Storage",
        "humidity_control": True,
        "estimated_rate": "₹9.50 - ₹12.50 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "A.K. Srivastava (Regional Manager)",
        "phone": "+91-512-2691240",
        "helpline": "1800-180-1551",
        "facilities": ["Railway Siding Integrated", "WDRA Electronic Warehouse Receipts", "Fire Protection & Hydrants", "Direct Mandi Transport"]
    },
    {
        "id": "upswc-barabanki",
        "name": "UPSWC State Agricultural Warehouse Barabanki",
        "category": "SWC Government Warehouse",
        "type": "cwc",
        "state": "Uttar Pradesh",
        "district": "Barabanki",
        "pincode": "225001",
        "address": "Faizabad Road, Near Railway Goods Shed, Barabanki, UP - 225001",
        "lat": 26.9248,
        "lng": 81.1843,
        "capacity_mt": 18000,
        "available_capacity_mt": 5400,
        "suitable_crops": ["Potato", "Mentha Oil", "Paddy", "Wheat", "Pulses"],
        "cold_storage": False,
        "temperature_range": "Ambient Ventilated",
        "humidity_control": True,
        "estimated_rate": "₹8.50 - ₹11 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "O.P. Verma (Manager)",
        "phone": "+91-5248-222380",
        "helpline": "1800-180-1551",
        "facilities": ["Mentha Drum Safe Storage", "WDRA e-NWR Loans", "Government Subsidies Applied", "Weighbridge (40 MT)"]
    },
    {
        "id": "cs-sitapur-lucknow",
        "name": "Awadh Kisan Cold Storage & Agro Logistics",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Uttar Pradesh",
        "district": "Lucknow",
        "pincode": "226021",
        "address": "Sitapur Road, Bakshi Ka Talab, Lucknow, UP - 226021",
        "lat": 26.9850,
        "lng": 80.9310,
        "capacity_mt": 9000,
        "available_capacity_mt": 2400,
        "suitable_crops": ["Potato", "Vegetables", "Mango", "Ginger", "Garlic"],
        "cold_storage": True,
        "temperature_range": "2°C to 6°C",
        "humidity_control": True,
        "estimated_rate": "₹195 - ₹240 per quintal / season",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Harish Rawat",
        "phone": "+91-94150-12890",
        "helpline": "+91-522-2733910",
        "facilities": ["Mango Ripening & Pre-cooling Chamber", "Backup Generator", "WDRA Accredited", "Direct Lucknow APMC Mandi Access"]
    },
    {
        "id": "cwc-nadesar-varanasi",
        "name": "CWC Central Warehouse Nadesar",
        "category": "CWC Government Warehouse",
        "type": "cwc",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "pincode": "221002",
        "address": "CWC Complex, Nadesar, Near Cantonment, Varanasi, UP - 221002",
        "lat": 25.3340,
        "lng": 82.9830,
        "capacity_mt": 20000,
        "available_capacity_mt": 5800,
        "suitable_crops": ["Paddy", "Wheat", "Vegetables", "Maize", "Pulses"],
        "cold_storage": False,
        "temperature_range": "Ambient",
        "humidity_control": True,
        "estimated_rate": "₹9.50 - ₹12 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Rajesh Kumar (Deputy Manager)",
        "phone": "+91-542-2503921",
        "helpline": "1800-180-1551",
        "facilities": ["e-NWR Pledge Loans via Union Bank", "50 MT Weighbridge", "Dunnage Mats Provided", "Quality Testing"]
    },

    # ------------------------------------------------------------
    # MAHARASHTRA
    # ------------------------------------------------------------
    {
        "id": "mswc-lasalgaon-nashik",
        "name": "MSWC State Warehouse Lasalgaon (Onion Terminal)",
        "category": "SWC Government Warehouse",
        "type": "cwc",
        "state": "Maharashtra",
        "district": "Nashik",
        "pincode": "422306",
        "address": "APMC Market Yard Road, Lasalgaon, Taluka Niphad, Nashik, Maharashtra - 422306",
        "lat": 20.1472,
        "lng": 74.2255,
        "capacity_mt": 22000,
        "available_capacity_mt": 6500,
        "suitable_crops": ["Onion", "Soybean", "Wheat", "Maize", "Garlic"],
        "cold_storage": False,
        "temperature_range": "Scientifically Ventilated Onion Structures",
        "humidity_control": True,
        "estimated_rate": "₹8 - ₹11 per quintal / month (Govt Subsidized)",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "S.B. Patil (Branch Manager MSWC)",
        "phone": "+91-2550-266124",
        "helpline": "1800-220-195",
        "facilities": ["Specialized Onion Chawl Ventilation", "WDRA e-NWR Loan Guarantee", "Direct APMC Lasalgaon Linkage", "Electronic Weighbridge (80 MT)"]
    },
    {
        "id": "cs-sahyadri-nashik",
        "name": "Sahyadri Farms Mega Cold Chain Hub",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Maharashtra",
        "district": "Nashik",
        "pincode": "422207",
        "address": "Survey 314, At Post Mohadi, Taluka Dindori, Nashik, Maharashtra - 422207",
        "lat": 20.0820,
        "lng": 73.8640,
        "capacity_mt": 18000,
        "available_capacity_mt": 4900,
        "suitable_crops": ["Grapes", "Tomato", "Pomegranate", "Onion", "Vegetables"],
        "cold_storage": True,
        "temperature_range": "-0.5°C to 12°C (Multi-Zone Humidity Controlled)",
        "humidity_control": True,
        "estimated_rate": "₹1.50 - ₹2.20 per kg / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Kisan Seva Kendra (Sahyadri FPC)",
        "phone": "+91-2557-259100",
        "helpline": "+91-1800-212-0022",
        "facilities": ["Export-grade Packhouse & Grading Lines", "Pre-cooling Tunnel", "Farmer Shareholder Rebates", "Reefer Fleet Support", "Testing Lab"]
    },
    {
        "id": "cs-pimpalgaon-nashik",
        "name": "Pimpalgaon APMC Cold Storage Terminal",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Maharashtra",
        "district": "Nashik",
        "pincode": "422209",
        "address": "Pimpalgaon Baswant APMC Complex, Mumbai-Agra Highway, Nashik - 422209",
        "lat": 20.1710,
        "lng": 73.9850,
        "capacity_mt": 10500,
        "available_capacity_mt": 3100,
        "suitable_crops": ["Tomato", "Grapes", "Onion", "Capsicum", "Vegetables"],
        "cold_storage": True,
        "temperature_range": "2°C to 10°C",
        "humidity_control": True,
        "estimated_rate": "₹140 - ₹180 per crate / season",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Vikas Shinde (APMC Secretary)",
        "phone": "+91-2554-251230",
        "helpline": "+91-2554-251444",
        "facilities": ["Immediate Auction Platform Integration", "Crate Washing & Sanitization", "Solar Backup Power", "Farmer Subsidized Tariff"]
    },
    {
        "id": "mswc-gultekdi-pune",
        "name": "MSWC Central Godown Pune APMC",
        "category": "SWC Government Warehouse",
        "type": "cwc",
        "state": "Maharashtra",
        "district": "Pune",
        "pincode": "411037",
        "address": "Market Yard, Gultekdi, Pune, Maharashtra - 411037",
        "lat": 18.4875,
        "lng": 73.8682,
        "capacity_mt": 26000,
        "available_capacity_mt": 7800,
        "suitable_crops": ["Soybean", "Wheat", "Jowar", "Pulses", "Jaggery", "Onion"],
        "cold_storage": False,
        "temperature_range": "Ambient",
        "humidity_control": True,
        "estimated_rate": "₹10 - ₹13 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Pravin Kulkarni (Regional Officer)",
        "phone": "+91-20-24263150",
        "helpline": "1800-220-195",
        "facilities": ["Direct Link to Pune APMC Market Yard", "Bank of Maharashtra e-NWR Loan Desk", "CCTV 24x7", "Fire Hydrants"]
    },
    {
        "id": "cs-narayangaon-pune",
        "name": "Junnar Taluka Tomato & Agro Cold Storage",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Maharashtra",
        "district": "Pune",
        "pincode": "410504",
        "address": "Pune-Nashik Highway, Narayangaon, Taluka Junnar, Pune - 410504",
        "lat": 19.1230,
        "lng": 73.9780,
        "capacity_mt": 8200,
        "available_capacity_mt": 2600,
        "suitable_crops": ["Tomato", "Onion", "Potato", "Pomegranate", "Exotic Veg"],
        "cold_storage": True,
        "temperature_range": "3°C to 12°C",
        "humidity_control": True,
        "estimated_rate": "₹130 - ₹170 per crate / month",
        "wdra_registered": False,
        "enwr_loan_eligible": False,
        "contact_person": "Sanjay Kale",
        "phone": "+91-98224-66311",
        "helpline": "+91-2132-242055",
        "facilities": ["Direct Link to Narayangaon Tomato Market", "Pre-Cooling Facilities", "Sorting Crates on Rent"]
    },
    {
        "id": "cwc-kalamna-nagpur",
        "name": "CWC Mega Central Warehouse Kalamna",
        "category": "CWC Government Warehouse",
        "type": "cwc",
        "state": "Maharashtra",
        "district": "Nagpur",
        "pincode": "440008",
        "address": "Kalamna Market Yard, Ring Road, Nagpur, Maharashtra - 440008",
        "lat": 21.1760,
        "lng": 79.1410,
        "capacity_mt": 35000,
        "available_capacity_mt": 10500,
        "suitable_crops": ["Cotton", "Soybean", "Paddy", "Orange / Citrus", "Wheat", "Chana"],
        "cold_storage": False,
        "temperature_range": "Ambient & Humidity Controlled",
        "humidity_control": True,
        "estimated_rate": "₹9.50 - ₹12 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "G.S. Meshram (Senior Warehouse Manager)",
        "phone": "+91-712-2680415",
        "helpline": "1800-180-1551",
        "facilities": ["Cotton Bale Stack Certified", "WDRA Electronic Negotiable Warehouse Receipts", "Private Railway Siding", "Pest Management"]
    },
    {
        "id": "cs-hingna-nagpur",
        "name": "Nagpur Orange & Citrus Cold Storage Chain",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Maharashtra",
        "district": "Nagpur",
        "pincode": "440028",
        "address": "MIDC Hingna Industrial Estate, Nagpur, Maharashtra - 440028",
        "lat": 21.0980,
        "lng": 79.0040,
        "capacity_mt": 9500,
        "available_capacity_mt": 3200,
        "suitable_crops": ["Orange", "Citrus", "Mosambi", "Soybean", "Vegetables"],
        "cold_storage": True,
        "temperature_range": "4°C to 8°C (Ethylene Controlled)",
        "humidity_control": True,
        "estimated_rate": "₹160 - ₹210 per quintal / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Milind Deshmukh",
        "phone": "+91-94221-55099",
        "helpline": "+91-7104-235610",
        "facilities": ["Waxing & Grading Line for Nagpur Mandarin", "Ethylene Scrubber", "Reefer Transportation to Delhi & Mumbai"]
    },
    {
        "id": "cs-jalgaon-banana",
        "name": "Jalgaon Banana Packhouse & Pre-Cooling Centre",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Maharashtra",
        "district": "Jalgaon",
        "pincode": "425507",
        "address": "Raver-Yawal Highway, District Jalgaon, Maharashtra - 425507",
        "lat": 21.2480,
        "lng": 75.9230,
        "capacity_mt": 11000,
        "available_capacity_mt": 3800,
        "suitable_crops": ["Banana", "Pulses", "Soybean", "Cotton", "Maize"],
        "cold_storage": True,
        "temperature_range": "13°C to 14.5°C (Chilled Banana Protocol)",
        "humidity_control": True,
        "estimated_rate": "₹1.20 - ₹1.80 per kg / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Anand Choudhary",
        "phone": "+91-94234-99881",
        "helpline": "+91-2584-252110",
        "facilities": ["Export Standard Banana Hanging Rail", "De-sapping & Chlorine Wash", "Pre-cooling to prevent ripening shock", "WDRA Accredited"]
    },
    {
        "id": "mswc-sangli-turmeric",
        "name": "Sangli Turmeric & Spices Terminal Warehouse",
        "category": "SWC Government Warehouse",
        "type": "cwc",
        "state": "Maharashtra",
        "district": "Sangli",
        "pincode": "416416",
        "address": "Market Yard, Sangli-Miraj Road, Sangli, Maharashtra - 416416",
        "lat": 16.8524,
        "lng": 74.5815,
        "capacity_mt": 19000,
        "available_capacity_mt": 5200,
        "suitable_crops": ["Turmeric", "Raisins (Kishmish)", "Jaggery", "Soybean", "Grapes"],
        "cold_storage": False,
        "temperature_range": "Dry Ambient Pest-free",
        "humidity_control": True,
        "estimated_rate": "₹11 - ₹14 per quintal / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Santosh Patil (Incharge)",
        "phone": "+91-233-2670512",
        "helpline": "1800-220-195",
        "facilities": ["Underground Cold Cellars for Turmeric", "e-NWR Pledge Loans for Turmeric Farmers", "Moisture Assay Lab", "Weighbridge (60 MT)"]
    },

    # ------------------------------------------------------------
    # PUNJAB & HARYANA
    # ------------------------------------------------------------
    {
        "id": "cwc-focalpoint-ludhiana",
        "name": "CWC Focal Point Warehouse Ludhiana",
        "category": "CWC Government Warehouse",
        "type": "cwc",
        "state": "Punjab",
        "district": "Ludhiana",
        "pincode": "141010",
        "address": "Focal Point Phase V, GT Road, Ludhiana, Punjab - 141010",
        "lat": 30.8840,
        "lng": 75.9120,
        "capacity_mt": 40000,
        "available_capacity_mt": 11000,
        "suitable_crops": ["Wheat", "Paddy (Basmati)", "Seed Potato", "Mustard", "Maize"],
        "cold_storage": False,
        "temperature_range": "Ambient",
        "humidity_control": True,
        "estimated_rate": "₹9 - ₹12 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Harpreet Singh (Chief Manager CWC)",
        "phone": "+91-161-2671840",
        "helpline": "1800-180-1551",
        "facilities": ["Full Covered Rail Siding", "WDRA e-NWR Loans with Punjab Gramin Bank", "Seed Certification Support", "60 MT Weighbridge"]
    },
    {
        "id": "cs-jalandhar-seedpotato",
        "name": "Doaba Kisan Seed Potato Cold Storage",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Punjab",
        "district": "Jalandhar",
        "pincode": "144008",
        "address": "Nakodar Road, Near APMC Mandi, Jalandhar, Punjab - 144008",
        "lat": 31.2980,
        "lng": 75.5620,
        "capacity_mt": 15000,
        "available_capacity_mt": 4200,
        "suitable_crops": ["Potato", "Seed Potato", "Peas", "Carrot", "Vegetables"],
        "cold_storage": True,
        "temperature_range": "2°C to 4°C (Seed dormancy protocol)",
        "humidity_control": True,
        "estimated_rate": "₹170 - ₹210 per bag (50kg) / season",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Jaswinder Singh Johal",
        "phone": "+91-98140-77881",
        "helpline": "+91-181-2254100",
        "facilities": ["Seed Treatment & Fungicide Line", "CO2 Extraction & Temperature Loggers", "WDRA Accredited", "Direct Pan-India Dispatch Support"]
    },
    {
        "id": "pswc-khanna-silo",
        "name": "PSWC Modern Grain Terminal & Silo Khanna",
        "category": "Modern Grain Silo (अनाज साइलो)",
        "type": "silo",
        "state": "Punjab",
        "district": "Ludhiana",
        "pincode": "141401",
        "address": "Near Asia's Largest Grain Mandi, GT Road, Khanna, Punjab - 141401",
        "lat": 30.7040,
        "lng": 76.2210,
        "capacity_mt": 50000,
        "available_capacity_mt": 14500,
        "suitable_crops": ["Wheat", "Paddy", "Maize"],
        "cold_storage": False,
        "temperature_range": "Steel Bulk Silo (Chilled Aerated)",
        "humidity_control": True,
        "estimated_rate": "₹8.50 - ₹11.50 per quintal / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Balwinder Singh (PSWC Incharge)",
        "phone": "+91-1628-226540",
        "helpline": "1800-180-1551",
        "facilities": ["Bagless Bulk Grain Unloading (Hydraulic Tippler)", "Pest-proof Steel Silo Storage", "Instant Weighing & Moisture Reading", "WDRA e-NWR Ready"]
    },
    {
        "id": "cwc-taraori-karnal",
        "name": "CWC Basmati Grain Terminal Taraori",
        "category": "CWC Government Warehouse",
        "type": "cwc",
        "state": "Haryana",
        "district": "Karnal",
        "pincode": "132116",
        "address": "GT Road, Taraori, District Karnal, Haryana - 132116",
        "lat": 29.8030,
        "lng": 76.9280,
        "capacity_mt": 36000,
        "available_capacity_mt": 9800,
        "suitable_crops": ["Paddy (Basmati)", "Wheat", "Mustard", "Barley"],
        "cold_storage": False,
        "temperature_range": "Ambient Aerated",
        "humidity_control": True,
        "estimated_rate": "₹10 - ₹13 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Naresh Chahal (Manager)",
        "phone": "+91-1745-242190",
        "helpline": "1800-180-1551",
        "facilities": ["Basmati Rice Export Accreditation", "Scientific Moisture Regulators", "WDRA Pledge Loans (up to 75% market value)", "60 MT Weighbridge"]
    },
    {
        "id": "cs-kunjpura-karnal",
        "name": "Karnal Kisan Cold Storage & Agro Hub",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Haryana",
        "district": "Karnal",
        "pincode": "132001",
        "address": "Kunjpura Road, Near Karnal Sugar Mill, Karnal, Haryana - 132001",
        "lat": 29.6860,
        "lng": 76.9920,
        "capacity_mt": 9500,
        "available_capacity_mt": 2900,
        "suitable_crops": ["Potato", "Vegetables", "Mushroom", "Carrot", "Tomato"],
        "cold_storage": True,
        "temperature_range": "1°C to 5°C",
        "humidity_control": True,
        "estimated_rate": "₹180 - ₹220 per quintal / season",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Joginder Mann",
        "phone": "+91-98120-33440",
        "helpline": "+91-184-2270911",
        "facilities": ["Mushroom Controlled Temperature Room", "Sorting & Packing Tables", "DG Power Backup", "Easy Access to Delhi Azadpur Supply"]
    },
    {
        "id": "hswc-sirsa-cotton",
        "name": "HSWC State Warehouse Sirsa",
        "category": "SWC Government Warehouse",
        "type": "cwc",
        "state": "Haryana",
        "district": "Sirsa",
        "pincode": "125055",
        "address": "Bhadra Road, Near Anaj Mandi, Sirsa, Haryana - 125055",
        "lat": 29.5320,
        "lng": 75.0280,
        "capacity_mt": 28000,
        "available_capacity_mt": 7400,
        "suitable_crops": ["Cotton", "Wheat", "Mustard", "Guar", "Paddy"],
        "cold_storage": False,
        "temperature_range": "Ambient",
        "humidity_control": True,
        "estimated_rate": "₹9 - ₹12 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Rakesh Dahiya (Incharge)",
        "phone": "+91-1666-220450",
        "helpline": "1800-180-1551",
        "facilities": ["Cotton Gidderbaha/Sirsa Belt Hub", "WDRA Electronic Receipts", "Fire Hydrants & Security", "Scientific Dunnage"]
    },

    # ------------------------------------------------------------
    # MADHYA PRADESH
    # ------------------------------------------------------------
    {
        "id": "cwc-manglia-indore",
        "name": "CWC Mega Logistics Warehouse Manglia",
        "category": "CWC Government Warehouse",
        "type": "cwc",
        "state": "Madhya Pradesh",
        "district": "Indore",
        "pincode": "453771",
        "address": "AB Road, Manglia, Indore, Madhya Pradesh - 453771",
        "lat": 22.8020,
        "lng": 75.9230,
        "capacity_mt": 38000,
        "available_capacity_mt": 11500,
        "suitable_crops": ["Soybean", "Wheat", "Gram (Chana)", "Maize", "Mustard", "Garlic"],
        "cold_storage": False,
        "temperature_range": "Ambient Ventilated",
        "humidity_control": True,
        "estimated_rate": "₹9 - ₹12.50 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Alok Mishra (Chief Warehouse Manager)",
        "phone": "+91-731-2802314",
        "helpline": "1800-180-1551",
        "facilities": ["Container Depot & Rail Siding", "WDRA e-NWR Loan Desk with Bank of India", "Lab Testing for Soybean Oil Content", "80 MT Weighbridge"]
    },
    {
        "id": "cs-sanwer-indore",
        "name": "Malwa Kisan Cold Storage & Logistics",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Madhya Pradesh",
        "district": "Indore",
        "pincode": "453551",
        "address": "Sanwer Road Industrial Area, Indore, MP - 453551",
        "lat": 22.7840,
        "lng": 75.8390,
        "capacity_mt": 12500,
        "available_capacity_mt": 3900,
        "suitable_crops": ["Potato", "Garlic", "Onion", "Ginger", "Carrot"],
        "cold_storage": True,
        "temperature_range": "1.5°C to 5°C",
        "humidity_control": True,
        "estimated_rate": "₹190 - ₹230 per quintal / season",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Ghanshyam Patidar",
        "phone": "+91-98260-44910",
        "helpline": "+91-731-2720450",
        "facilities": ["Garlic Special Dehumidified Chamber", "Automatic Digital Temperature Loggers", "WDRA Accredited", "Potato Grading Machine"]
    },
    {
        "id": "cs-mandsaur-garlic",
        "name": "Mandsaur Garlic & Spices Cold Terminal",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Madhya Pradesh",
        "district": "Mandsaur",
        "pincode": "458001",
        "address": "Near Krishi Upaj Mandi, Mandsaur, Madhya Pradesh - 458001",
        "lat": 24.0720,
        "lng": 75.0710,
        "capacity_mt": 16000,
        "available_capacity_mt": 4800,
        "suitable_crops": ["Garlic", "Coriander", "Fenugreek", "Onion", "Soybean"],
        "cold_storage": True,
        "temperature_range": "-1°C to 2°C (Special Low-Moisture Garlic Protocol)",
        "humidity_control": True,
        "estimated_rate": "₹210 - ₹260 per quintal / season",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Bhagwandas Jain",
        "phone": "+91-94251-22441",
        "helpline": "+91-7422-255190",
        "facilities": ["India's Premier Garlic Dehumidified Storage", "Odor Prevention Air Circulation", "WDRA e-NWR Loan Assistance", "Direct Mandi Dispatch"]
    },
    {
        "id": "mpwlc-maksi-ujjain",
        "name": "MPWLC State Warehouse Maksi Road Ujjain",
        "category": "SWC Government Warehouse",
        "type": "cwc",
        "state": "Madhya Pradesh",
        "district": "Ujjain",
        "pincode": "456010",
        "address": "Maksi Road, Industrial Estate, Ujjain, MP - 456010",
        "lat": 23.1820,
        "lng": 75.7990,
        "capacity_mt": 25000,
        "available_capacity_mt": 7100,
        "suitable_crops": ["Soybean", "Gram (Chana)", "Wheat", "Garlic", "Mustard"],
        "cold_storage": False,
        "temperature_range": "Ambient Aerated",
        "humidity_control": True,
        "estimated_rate": "₹8.50 - ₹11 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Kamlesh Sharma (Superintendent)",
        "phone": "+91-734-2521880",
        "helpline": "1800-180-1551",
        "facilities": ["MP State Civil Supplies Linkage", "WDRA Electronic Negotiable Warehouse Receipts", "Moisture Testing Meter", "60 MT Weighbridge"]
    },

    # ------------------------------------------------------------
    # GUJARAT
    # ------------------------------------------------------------
    {
        "id": "cs-deesa-potato-capital",
        "name": "Deesa Mega Potato Cold Storage Hub",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Gujarat",
        "district": "Banaskantha",
        "pincode": "385535",
        "address": "Palanpur-Deesa Highway, Deesa, Banaskantha, Gujarat - 385535",
        "lat": 24.2580,
        "lng": 72.1810,
        "capacity_mt": 22000,
        "available_capacity_mt": 6800,
        "suitable_crops": ["Potato", "Seed Potato", "Carrot", "Groundnut", "Mustard"],
        "cold_storage": True,
        "temperature_range": "2°C to 4°C (Multi-Tier Automated Cooling)",
        "humidity_control": True,
        "estimated_rate": "₹170 - ₹210 per bag (50kg) / season",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Pravinbhai Patel",
        "phone": "+91-98250-11299",
        "helpline": "+91-2744-220150",
        "facilities": ["India's Potato Capital Flagship Storage", "French Fry & Processing Grade Temperature Protocol", "WDRA e-NWR Loans", "Automated Elevators"]
    },
    {
        "id": "cwc-unjha-jeera",
        "name": "CWC Unjha Spices & Cumin Warehouse Terminal",
        "category": "CWC Government Warehouse",
        "type": "cwc",
        "state": "Gujarat",
        "district": "Mehsana",
        "pincode": "384170",
        "address": "Near APMC Market Yard, Unjha, Mehsana, Gujarat - 384170",
        "lat": 23.8040,
        "lng": 72.3920,
        "capacity_mt": 28000,
        "available_capacity_mt": 8200,
        "suitable_crops": ["Cumin (Jeera)", "Fennel (Saunf)", "Mustard", "Psyllium (Isabgol)", "Castor"],
        "cold_storage": False,
        "temperature_range": "Scientifically Dehumidified Spice Storage",
        "humidity_control": True,
        "estimated_rate": "₹12 - ₹16 per quintal / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "K.M. Vaghela (Chief Manager)",
        "phone": "+91-2767-252410",
        "helpline": "1800-180-1551",
        "facilities": ["World's Largest Cumin Mandi Terminal", "AGMARK Testing Laboratory on Site", "WDRA e-NWR Instant Bank Credit", "Pest & Beetle Proofing"]
    },
    {
        "id": "gswc-gondal-groundnut",
        "name": "GSWC Groundnut & Agro Warehouse Gondal",
        "category": "SWC Government Warehouse",
        "type": "cwc",
        "state": "Gujarat",
        "district": "Rajkot",
        "pincode": "360311",
        "address": "National Highway 27, Near APMC Yard, Gondal, Rajkot - 360311",
        "lat": 21.9610,
        "lng": 70.8010,
        "capacity_mt": 24000,
        "available_capacity_mt": 7100,
        "suitable_crops": ["Groundnut", "Cotton", "Chilli", "Onion", "Wheat", "Sesame"],
        "cold_storage": False,
        "temperature_range": "Ambient",
        "humidity_control": True,
        "estimated_rate": "₹9.50 - ₹12 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Mansukhbhai Bhalodiya",
        "phone": "+91-2825-224190",
        "helpline": "1800-233-0195",
        "facilities": ["Saurashtra Groundnut Hub", "e-NWR Pledge Loans via SBI & BOB", "Dharam Kanta (60 MT)", "Stack Fumigation Included"]
    },

    # ------------------------------------------------------------
    # RAJASTHAN
    # ------------------------------------------------------------
    {
        "id": "rswc-kukas-jaipur",
        "name": "RSWC Central Warehouse Kukas",
        "category": "SWC Government Warehouse",
        "type": "cwc",
        "state": "Rajasthan",
        "district": "Jaipur",
        "pincode": "302028",
        "address": "Delhi-Jaipur Highway NH-48, Kukas, Jaipur, Rajasthan - 302028",
        "lat": 27.0540,
        "lng": 75.8940,
        "capacity_mt": 26000,
        "available_capacity_mt": 7900,
        "suitable_crops": ["Mustard", "Wheat", "Barley", "Gram (Chana)", "Bajra", "Guar"],
        "cold_storage": False,
        "temperature_range": "Ambient",
        "humidity_control": True,
        "estimated_rate": "₹8.50 - ₹11.50 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Surendra Singh Rathore (Incharge)",
        "phone": "+91-141-2670311",
        "helpline": "1800-180-1551",
        "facilities": ["WDRA Registered Electronic Receipts", "Moisture & Quality Assay", "Fire Safety System", "Subsidized Tariffs for Small Farmers"]
    },
    {
        "id": "cs-chomu-jaipur",
        "name": "Chomu Kisan Cold Storage & Vegetable Terminal",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Rajasthan",
        "district": "Jaipur",
        "pincode": "303702",
        "address": "Sikar Road, Near Mandi, Chomu, Jaipur, Rajasthan - 303702",
        "lat": 27.1720,
        "lng": 75.7210,
        "capacity_mt": 9000,
        "available_capacity_mt": 2700,
        "suitable_crops": ["Potato", "Carrot", "Tomato", "Cauliflower", "Vegetables"],
        "cold_storage": True,
        "temperature_range": "2°C to 5°C",
        "humidity_control": True,
        "estimated_rate": "₹185 - ₹225 per quintal / season",
        "wdra_registered": False,
        "enwr_loan_eligible": False,
        "contact_person": "Ratan Lal Saini",
        "phone": "+91-94140-55120",
        "helpline": "+91-1423-221088",
        "facilities": ["Chomu Vegetable Belt Hub", "Direct Sikar-Jaipur Transport Support", "DG Generator Set"]
    },
    {
        "id": "rswc-nokha-bikaner",
        "name": "Bikaner Pulses & Moth Godown Nokha",
        "category": "SWC Government Warehouse",
        "type": "cwc",
        "state": "Rajasthan",
        "district": "Bikaner",
        "pincode": "334803",
        "address": "Krishi Mandi Road, Nokha, Bikaner, Rajasthan - 334803",
        "lat": 27.6010,
        "lng": 73.4210,
        "capacity_mt": 20000,
        "available_capacity_mt": 5800,
        "suitable_crops": ["Moong (Green Gram)", "Moth", "Guar", "Mustard", "Wheat", "Cumin"],
        "cold_storage": False,
        "temperature_range": "Dry Desert Ambient",
        "humidity_control": True,
        "estimated_rate": "₹8 - ₹10.50 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Ramawtar Bishnoi",
        "phone": "+91-1531-220140",
        "helpline": "1800-180-1551",
        "facilities": ["India's Moth & Guar Capital", "Pledge Finance with Rajasthan Marudhara Gramin Bank", "Fumigation Included", "60 MT Weighbridge"]
    },
    {
        "id": "cwc-chambal-kota",
        "name": "CWC Central Warehouse Chambal Kota",
        "category": "CWC Government Warehouse",
        "type": "cwc",
        "state": "Rajasthan",
        "district": "Kota",
        "pincode": "324003",
        "address": "Large Scale Industrial Area, Jhalawar Road, Kota, Rajasthan - 324003",
        "lat": 25.1480,
        "lng": 75.8640,
        "capacity_mt": 29000,
        "available_capacity_mt": 8400,
        "suitable_crops": ["Soybean", "Coriander (Dhaniya)", "Mustard", "Wheat", "Garlic"],
        "cold_storage": False,
        "temperature_range": "Ambient",
        "humidity_control": True,
        "estimated_rate": "₹9.50 - ₹12 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "M.L. Meena (Manager)",
        "phone": "+91-744-2481050",
        "helpline": "1800-180-1551",
        "facilities": ["Hadoti Soybean & Coriander Hub", "WDRA e-NWR Direct Bank Loans", "Railway Siding", "Moisture Test Lab"]
    },

    # ------------------------------------------------------------
    # BIHAR
    # ------------------------------------------------------------
    {
        "id": "cwc-gulabbagh-purnea",
        "name": "CWC Mega Maize Terminal Gulabbagh",
        "category": "CWC Government Warehouse",
        "type": "cwc",
        "state": "Bihar",
        "district": "Purnea",
        "pincode": "854326",
        "address": "Gulabbagh Mandi Area, NH-31, Purnea, Bihar - 854326",
        "lat": 25.7720,
        "lng": 87.5110,
        "capacity_mt": 36000,
        "available_capacity_mt": 10200,
        "suitable_crops": ["Maize", "Paddy", "Jute", "Wheat", "Potato"],
        "cold_storage": False,
        "temperature_range": "Scientifically Ventilated Grain Storage",
        "humidity_control": True,
        "estimated_rate": "₹8.50 - ₹11.50 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Arun Kumar Jha (Chief Manager CWC)",
        "phone": "+91-6454-242318",
        "helpline": "1800-180-1551",
        "facilities": ["Asia's Largest Maize Market Terminal", "WDRA e-NWR Fast Loan Sanctions", "Direct Train Siding to Poultry Feed Hubs", "Pest Management"]
    },
    {
        "id": "cs-kasba-purnea",
        "name": "Seemanchal Kisan Cold Storage",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Bihar",
        "district": "Purnea",
        "pincode": "854330",
        "address": "Kasba Road, Near Bypass, Purnea, Bihar - 854330",
        "lat": 25.8450,
        "lng": 87.5320,
        "capacity_mt": 10000,
        "available_capacity_mt": 2900,
        "suitable_crops": ["Potato", "Vegetables", "Maize Seed", "Ginger"],
        "cold_storage": True,
        "temperature_range": "2°C to 4°C",
        "humidity_control": True,
        "estimated_rate": "₹180 - ₹220 per quintal / season",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Shashi Bhushan Roy",
        "phone": "+91-94312-77110",
        "helpline": "+91-6454-228100",
        "facilities": ["High-Humidity Potato Storage", "DG Backup 24/7", "WDRA Accredited", "Direct Guwahati & Kolkata Transport Links"]
    },
    {
        "id": "cs-bela-muzaffarpur",
        "name": "Muzaffarpur Litchi & Horticulture Cold Chain",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Bihar",
        "district": "Muzaffarpur",
        "pincode": "842005",
        "address": "Bela Industrial Area, Phase II, Muzaffarpur, Bihar - 842005",
        "lat": 26.1120,
        "lng": 85.4210,
        "capacity_mt": 8500,
        "available_capacity_mt": 2300,
        "suitable_crops": ["Shahi Litchi", "Mango", "Potato", "Vegetables", "Banana"],
        "cold_storage": True,
        "temperature_range": "1°C to 6°C (Rapid Pre-Cooling)",
        "humidity_control": True,
        "estimated_rate": "₹2 - ₹3 per kg / month (Seasonal Litchi Protocol)",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Prabhat Singh",
        "phone": "+91-94314-11880",
        "helpline": "+91-621-2274190",
        "facilities": ["Shahi Litchi Cold Chain Protocol", "Sulphur Treatment & Sorting Line", "Refrigerated Van Dispatch", "WDRA e-NWR Loans"]
    },

    # ------------------------------------------------------------
    # KARNATAKA, ANDHRA PRADESH & TELANGANA
    # ------------------------------------------------------------
    {
        "id": "apmc-kolar-tomato",
        "name": "Kolar APMC Tomato Cold Chain & Packhouse",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Karnataka",
        "district": "Kolar",
        "pincode": "563101",
        "address": "APMC Yard, Bangarpet Road, Kolar, Karnataka - 563101",
        "lat": 13.1360,
        "lng": 78.1340,
        "capacity_mt": 8500,
        "available_capacity_mt": 2600,
        "suitable_crops": ["Tomato", "Mango", "Capsicum", "Beans", "Vegetables"],
        "cold_storage": True,
        "temperature_range": "8°C to 12°C (Controlled Ripening & Storage)",
        "humidity_control": True,
        "estimated_rate": "₹120 - ₹160 per plastic crate / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "V. Manjunatha (APMC Secretary)",
        "phone": "+91-8152-222380",
        "helpline": "+91-8152-224411",
        "facilities": ["Asia's Second Largest Tomato Market Hub", "Pre-cooling Chambers to extend shelf life by 14 days", "Crate Washing Facility", "Bengaluru/Chennai Transport Hub"]
    },
    {
        "id": "cwc-belagavi-hub",
        "name": "CWC Central Warehouse Belagavi",
        "category": "CWC Government Warehouse",
        "type": "cwc",
        "state": "Karnataka",
        "district": "Belagavi",
        "pincode": "590010",
        "address": "Udyambag Industrial Estate, Belagavi, Karnataka - 590010",
        "lat": 15.8280,
        "lng": 74.5020,
        "capacity_mt": 18000,
        "available_capacity_mt": 5200,
        "suitable_crops": ["Onion", "Soybean", "Maize", "Paddy", "Sugar", "Chilli"],
        "cold_storage": False,
        "temperature_range": "Ambient",
        "humidity_control": True,
        "estimated_rate": "₹9.50 - ₹12 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "C.H. Naik (Warehouse Manager)",
        "phone": "+91-831-2441890",
        "helpline": "1800-180-1551",
        "facilities": ["Karnataka-Maharashtra Border Transit Point", "WDRA Electronic Warehouse Receipts", "Weighbridge (60 MT)", "Pest Management"]
    },
    {
        "id": "cwc-guntur-chilli",
        "name": "CWC Mega Red Chilli Terminal Guntur",
        "category": "CWC Government Warehouse",
        "type": "cwc",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "pincode": "522004",
        "address": "Near Mirchi Yard, Narakodur Road, Guntur, Andhra Pradesh - 522004",
        "lat": 16.2910,
        "lng": 80.4520,
        "capacity_mt": 42000,
        "available_capacity_mt": 12800,
        "suitable_crops": ["Dry Red Chilli", "Turmeric", "Cotton", "Paddy", "Tobacco"],
        "cold_storage": False,
        "temperature_range": "Dehumidified & Cold-Assisted (3°C to 10°C in specialized chambers)",
        "humidity_control": True,
        "estimated_rate": "₹160 - ₹210 per quintal (6 months chilli package)",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "K. Venkata Rao (Senior Regional Manager)",
        "phone": "+91-863-2234091",
        "helpline": "1800-180-1551",
        "facilities": ["Asia's Largest Dry Red Chilli Storage Complex", "Colour Retention Protocol", "Andhra Bank & SBI Instant Pledge Loan (up to 75%)", "Fire Protection"]
    },
    {
        "id": "cs-kurnool-onion",
        "name": "Kurnool Onion & Bengal Gram Cold Storage",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "Andhra Pradesh",
        "district": "Kurnool",
        "pincode": "518003",
        "address": "Bellary Road, Near APMC Market, Kurnool, Andhra Pradesh - 518003",
        "lat": 15.8280,
        "lng": 78.0370,
        "capacity_mt": 13500,
        "available_capacity_mt": 4100,
        "suitable_crops": ["Onion", "Gram (Chana)", "Groundnut", "Chilli"],
        "cold_storage": True,
        "temperature_range": "1°C to 4°C",
        "humidity_control": True,
        "estimated_rate": "₹180 - ₹220 per quintal / season",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "P. Sudhakar Reddy",
        "phone": "+91-94402-11840",
        "helpline": "+91-8518-231900",
        "facilities": ["Sprout Suppression Onion Storage", "WDRA Certified", "50 MT Dharam Kanta", "Bank Loan Assistance"]
    },
    {
        "id": "tswc-warangal-turmeric",
        "name": "TSWC Warangal Turmeric & Grain Terminal",
        "category": "SWC Government Warehouse",
        "type": "cwc",
        "state": "Telangana",
        "district": "Warangal",
        "pincode": "506006",
        "address": "Enumamula APMC Complex, Warangal, Telangana - 506006",
        "lat": 17.9810,
        "lng": 79.6240,
        "capacity_mt": 25000,
        "available_capacity_mt": 7400,
        "suitable_crops": ["Cotton", "Turmeric", "Paddy", "Maize", "Chilli"],
        "cold_storage": False,
        "temperature_range": "Ambient",
        "humidity_control": True,
        "estimated_rate": "₹9 - ₹12 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "M. Srinivas (Superintendent)",
        "phone": "+91-870-2521340",
        "helpline": "1800-180-1551",
        "facilities": ["Enumamula Asia's 2nd Largest Market Yard", "WDRA Electronic Receipts for Telengana Grameena Bank", "Electronic Weighbridge", "Quality Assay"]
    },

    # ------------------------------------------------------------
    # WEST BENGAL & HIMACHAL PRADESH
    # ------------------------------------------------------------
    {
        "id": "cs-tarakeswar-hooghly",
        "name": "Tarakeswar Mega Potato Cold Storage Hub",
        "category": "Cold Storage (शीत गृह)",
        "type": "cold",
        "state": "West Bengal",
        "district": "Hooghly",
        "pincode": "712410",
        "address": "Tarakeswar-Champadanga Road, Hooghly, West Bengal - 712410",
        "lat": 22.8870,
        "lng": 88.0210,
        "capacity_mt": 18000,
        "available_capacity_mt": 5300,
        "suitable_crops": ["Potato", "Vegetables", "Pointed Gourd (Parwal)"],
        "cold_storage": True,
        "temperature_range": "2°C to 4°C",
        "humidity_control": True,
        "estimated_rate": "₹160 - ₹195 per quintal / season (Bengal Govt Regulated Tariff)",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Subhash Ghosh (Secretary)",
        "phone": "+91-94341-22990",
        "helpline": "+91-3212-276140",
        "facilities": ["Bengal's Potato Heartland Flagship", "State Regulated Fair Rental Scheme", "Automatic Elevator & Grading", "Direct Kolkata Posta Mandi Supply"]
    },
    {
        "id": "wbswc-burdwan-rice",
        "name": "WBSWC Burdwan Rice & Grain Warehouse",
        "category": "SWC Government Warehouse",
        "type": "cwc",
        "state": "West Bengal",
        "district": "Purba Bardhaman",
        "pincode": "713101",
        "address": "Memari GT Road, Bardhaman, West Bengal - 713101",
        "lat": 23.2380,
        "lng": 87.8650,
        "capacity_mt": 32000,
        "available_capacity_mt": 8900,
        "suitable_crops": ["Paddy", "Rice", "Wheat", "Mustard", "Jute"],
        "cold_storage": False,
        "temperature_range": "Ambient Aerated",
        "humidity_control": True,
        "estimated_rate": "₹8.50 - ₹11.50 per bag / month",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "Anirban Mukherjee (Manager)",
        "phone": "+91-342-2551420",
        "helpline": "1800-180-1551",
        "facilities": ["Burdwan Rice Bowl Flagship Depot", "WDRA e-NWR Loan Desk with UCO Bank", "Dunnage Mats", "Scientific Fumigation"]
    },
    {
        "id": "hpmc-jarol-tikkar-shimla",
        "name": "HPMC Controlled Atmosphere (CA) Cold Store",
        "category": "Controlled Atmosphere (CA) Store",
        "type": "cold",
        "state": "Himachal Pradesh",
        "district": "Shimla",
        "pincode": "171203",
        "address": "Jarol Tikkar, Kotkhai Valley, Shimla, Himachal Pradesh - 171203",
        "lat": 31.1210,
        "lng": 77.5320,
        "capacity_mt": 9500,
        "available_capacity_mt": 2800,
        "suitable_crops": ["Apple", "Pear", "Cherry", "Garlic", "Stone Fruits"],
        "cold_storage": True,
        "temperature_range": "0.5°C to 2°C (O2 1.5%, CO2 1.0% CA Sealed)",
        "humidity_control": True,
        "estimated_rate": "₹1.80 - ₹2.50 per kg / month (Preserves crispness up to 8 months)",
        "wdra_registered": True,
        "enwr_loan_eligible": True,
        "contact_person": "HPMC Regional Incharge",
        "phone": "+91-1783-255012",
        "helpline": "+91-177-2652199",
        "facilities": ["Ultra Low Oxygen (ULO) CA Technology", "Electronic Color Sorter & Grader", "HPMC Government Subsidy Scheme", "Direct Delhi Azadpur Reefer Despatch"]
    }
]

def find_nearest_storage_facilities(
    lat=None,
    lon=None,
    radius_km=100.0,
    category="all",
    crop=None,
    query=None,
    limit=50
):
    """
    Search, filter, and sort verified Indian storage facilities.
    
    Args:
        lat (float): User's latitude.
        lon (float): User's longitude.
        radius_km (float): Maximum radius in km. Set to <= 0 or > 1000 for all-India.
        category (str): 'all', 'cold', 'cwc', 'wdra', 'silo', 'warehouse'.
        crop (str): Filter by crop suitability (e.g., 'Potato', 'Wheat', 'Onion').
        query (str): Text search for district, state, pin, address, or name.
        limit (int): Max number of results.
    
    Returns:
        dict: {
            'success': True,
            'facilities': [...],
            'total_found': int,
            'nearest_distance_km': float or None,
            'cold_count': int,
            'wdra_count': int
        }
    """
    has_coords = lat is not None and lon is not None
    cat_filter = (category or "all").lower().strip()
    crop_filter = (crop or "").lower().strip()
    text_query = (query or "").lower().strip()
    max_radius = float(radius_km) if radius_km and float(radius_km) > 0 else 999999.0

    matches = []

    for facility in INDIAN_STORAGE_DATABASE:
        # Category filter
        if cat_filter != "all":
            if cat_filter in {"cold", "cold_storage"}:
                if not facility.get("cold_storage"):
                    continue
            elif cat_filter in {"cwc", "swc", "government"}:
                if facility.get("type") not in {"cwc", "swc"}:
                    continue
            elif cat_filter in {"wdra", "enwr"}:
                if not facility.get("wdra_registered"):
                    continue
            elif cat_filter in {"silo"}:
                if facility.get("type") != "silo":
                    continue
            elif cat_filter in {"warehouse", "dry"}:
                if facility.get("cold_storage"):
                    continue

        # Crop suitability filter
        if crop_filter:
            crops_lower = [c.lower() for c in facility.get("suitable_crops", [])]
            direct_match = any(crop_filter in c for c in crops_lower)
            is_perishable = any(p in crop_filter for p in ("potato", "tomato", "onion", "apple", "fruit", "carrot", "vegetable", "आलू", "टमाटर", "प्याज", "सब्जी", "फल"))
            is_grain = any(g in crop_filter for g in ("wheat", "paddy", "rice", "mustard", "maize", "soybean", "chana", "gram", "pulse", "गेहूं", "धान", "चावल", "सरसों", "मक्का", "सोयाबीन", "चना", "दाल"))
            
            crop_class_match = (is_perishable and facility.get("cold_storage")) or (is_grain and not facility.get("cold_storage"))
            if not (direct_match or crop_class_match):
                continue

        # Text search (district, state, pincode, name, address)
        if text_query:
            searchable_text = " ".join([
                facility.get("name", ""),
                facility.get("district", ""),
                facility.get("state", ""),
                facility.get("pincode", ""),
                facility.get("address", ""),
                " ".join(facility.get("suitable_crops", []))
            ]).lower()
            if text_query not in searchable_text:
                continue

        # Compute distance if coordinates available
        distance_km = None
        if has_coords:
            distance_km = haversine_distance_km(lat, lon, facility["lat"], facility["lng"])
            if max_radius < 999990.0 and distance_km > max_radius:
                continue

        item = dict(facility)
        item["distance_km"] = round(distance_km, 1) if distance_km is not None else None
        matches.append(item)

    # Sort: by distance if coords provided, else alphabetically by state & district
    if has_coords:
        matches.sort(key=lambda x: (x["distance_km"] if x["distance_km"] is not None else 999999))
    else:
        matches.sort(key=lambda x: (x.get("state", ""), x.get("district", ""), x.get("name", "")))

    # Compute summary metrics
    cold_count = sum(1 for f in matches if f.get("cold_storage"))
    wdra_count = sum(1 for f in matches if f.get("wdra_registered"))
    nearest_dist = matches[0]["distance_km"] if (matches and matches[0]["distance_km"] is not None) else None

    return {
        "success": True,
        "facilities": matches[:limit],
        "total_found": len(matches),
        "nearest_distance_km": nearest_dist,
        "cold_storage_count": cold_count,
        "wdra_count": wdra_count,
        "has_gps": has_coords,
        "source": "verified_database"
    }

def get_all_districts_and_states():
    """Return unique states and districts present in the storage database."""
    states_dict = {}
    for f in INDIAN_STORAGE_DATABASE:
        s = f.get("state", "")
        d = f.get("district", "")
        if s:
            states_dict.setdefault(s, set()).add(d)
    return {s: sorted(list(ds)) for s, ds in sorted(states_dict.items())}

